name: Build & Deploy (Production)

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build (Production)
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/seventv/eventapi:${{ github.sha }}
            ghcr.io/seventv/eventapi:latest

  deploy:
    name: Deploy (Production)
    runs-on: self-hosted
    needs: 
      - build

    steps:
      - name: Deploy Production Server
        uses: fifsky/ssh-action@master
        with:
          command: docker pull ghcr.io/seventv/autodeploy:latest && docker run --net=host -v /opt/autodeploy/config.yaml:/app/config.yaml -v /opt/autodeploy/private.key:/app/private.key ghcr.io/seventv/autodeploy:latest --service events --tag ${{ github.sha }}
          host: ${{ secrets.DEPLOY_HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
